server:
  port: 8080
  servlet:
    context-path:


mq:
  address: 192.168.243.70:9876


event:
  bus:
    port: 9906

logging:
  config: classpath:logback/logback-spring.xml

spring:
  profiles:
    active: dev

